databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    region: oregon
    plan: free

services:
  - type: web
    name: zunda
    runtime: python  # runtimeを指定
    env: python
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
